version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #do not try to create a volume mapping for this path.
      - .:/app #create a volume mapping from current workdir (.) to the /app within the container.
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #do not try to create a volume mapping for this path.
      - .:/app #create a volume mapping from current workdir (.) to the /app within the container.